# Generated by Django 3.0 on 2021-04-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='csvdatamodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_price', models.CharField(default='', max_length=50)),
                ('beds', models.CharField(default='', max_length=50)),
                ('baths', models.CharField(default='', max_length=50)),
                ('sqft', models.CharField(max_length=50)),
                ('year_built', models.CharField(max_length=50)),
                ('lot_size', models.CharField(max_length=50)),
                ('basement', models.CharField(max_length=50)),
                ('restaurants', models.CharField(max_length=50)),
                ('groceries', models.CharField(max_length=50)),
                ('nightlife', models.CharField(max_length=50)),
                ('cafes', models.CharField(max_length=50)),
                ('shopping', models.CharField(max_length=50)),
                ('arts_entertainment', models.CharField(max_length=50)),
                ('beauty_spas', models.CharField(max_length=50)),
                ('active_life', models.CharField(max_length=50)),
                ('median_age', models.CharField(max_length=50)),
                ('married', models.CharField(max_length=50)),
                ('college_grad', models.CharField(max_length=50)),
                ('property_tax', models.CharField(default='', max_length=50)),
                ('insurance', models.CharField(default='', max_length=50)),
                ('median_school', models.CharField(max_length=50)),
                ('num_school', models.CharField(max_length=50)),
                ('tx_year', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'csvdatamodel',
            },
        ),
        migrations.CreateModel(
            name='pricemodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sqft', models.CharField(max_length=50)),
                ('restaurants', models.CharField(max_length=50)),
                ('groceries', models.CharField(max_length=50)),
                ('nightlife', models.CharField(max_length=50)),
                ('cafes', models.CharField(max_length=50)),
                ('shopping', models.CharField(max_length=50)),
                ('arts_entertainment', models.CharField(max_length=50)),
                ('beauty_spas', models.CharField(max_length=50)),
                ('active_life', models.CharField(max_length=50)),
                ('median_age', models.CharField(max_length=50)),
                ('married', models.CharField(max_length=50)),
                ('college_grad', models.CharField(max_length=50)),
                ('property_tax', models.CharField(default='', max_length=50)),
                ('median_school', models.CharField(max_length=50)),
                ('num_school', models.CharField(max_length=50)),
                ('tx_year', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'pricemodel',
            },
        ),
        migrations.CreateModel(
            name='usermodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('passwd', models.CharField(max_length=40)),
                ('cwpasswd', models.CharField(max_length=40)),
                ('mobileno', models.CharField(default='', max_length=12)),
                ('status', models.CharField(default='', max_length=40)),
            ],
            options={
                'db_table': 'userregister',
            },
        ),
    ]
